### ISSUE TITLE
[MinimalFooter] Add Instagram to `socialLinks`

### ISSUE THREAD

**Issue by simurai** [primer/brand#266]
This came up in https://github.com/github/githubuniverse.com/issues/1711#issuecomment-1539633063. The request would be to add an `instagram` option to the `socialLinks` and link to http://instagram.com/github.

**Comment by JoshBowdenConcepts** [comment]
@rezrah @raytalks just because this was on my mind this addition does follow the [Instagram guidelines](https://about.meta.com/brand/resources/instagram/icons/) mostly except for the following issue.

- A minimum size ensures that the impact and legibility of the glyph are not compromised in the application. Always maintain their set proportions and never show the glyph smaller than 29x29 pixels.

We could solve this by increasing the size of the glyphs for all our icons at this time. Would this be a viable solution or should we reach out to design?

**Comment by raytalks** [comment]
Great question, I'd like to check with design. 
@ajashams do you know?

**Comment by ajashams** [comment]
Im in agreement with this @JoshBowdenConcepts 👍 .
