### ISSUE TITLE
🐛 [BUG] - AnchorNav starting blank on mobile devices

### ISSUE THREAD

**Issue by sergioalvz** [primer/brand#319]
### Describe the bug

Under certain circumstances, the `AnchorNav` renders only the arrow and not the section title.

See the following example:

https://github.com/primer/brand/assets/3042654/1336d3a3-c510-47cc-9288-76bc0c898556

### Reproduction steps

```bash
1. Go to https://primer.style/brand/storybook/?path=/story/components-anchornav-features--fewer-anchor-links&args=offset:500
2. Make sure the offset is, at least, `500px`
3. Use a narrow screen size
4. Scroll slowly until seeing the `AnchorNav` component
5. See error
```

### Expected behavior

```bash
1. Go to https://primer.style/brand/storybook/?path=/story/components-anchornav-features--fewer-anchor-links&args=offset:500
2. Make sure the offset is, at least, `500px`
3. Use a narrow screen size
4. Scroll slowly until seeing the `AnchorNav` component
5. The `AnchorNav` shows the first section title
```

### Screenshots

```bash
See video attached above.
```

**Comment by JoshBowdenConcepts** [comment]
The Problem:
- Since we have an API option where we can choose where the intersectionOption for each link is possibly set to the middle the offset that we created makes the UI feel odd but it works as the API expects it to.

Questions:
- To update this I would make sure that the first AnchorNav.Link always starts with a top IntersectionObserver and it would effectively ignore the middle option that would be set on the rest. Is this ok and how would we demonstrate this to our users?
