### ISSUE TITLE
🐛 [BUG] - Animating hero (above the fold)

### ISSUE THREAD

**Issue by simurai** [primer/brand#361]
### Describe the bug

This came up in https://github.com/github/githubuniverse.com/pull/1761#issuecomment-1649321470. 

### Reproduction steps

1. Click the Preview link in https://github.com/github/githubuniverse.com/pull/1761
2. You might have to reload and/or resize the browser window, but usually the "logo" does not animate in and stays blank
3. When you scroll up/down, animation works

### Expected behavior

1. Click the Preview link in https://github.com/github/githubuniverse.com/pull/1761
2. The "logo" should animate

I played around with [`runOnce` + `visibilityOptions`](https://github.com/github/githubuniverse.com/pull/1761/files#diff-522719ccbde5521f638c7d36821e91128ceb08b7812a1a7437b5d2cf96c8f660R55), but that doesn't seem to really help. Interestingly, if I remove all the other `<AnimationProvider>` on the page it works fine. 🤔

Maybe there is something that confuses the `animationTrigger` since the animation is in the hero (above the fold) and is not "scrolled into view". And option might be to add a `animationTrigger='on-load'` for animations that should just play as soon as the page loads (regardless of body scroll)?

### Screenshots

See https://github.com/github/githubuniverse.com/pull/1761#issuecomment-1649321470

### Browsers

Chrome

### OS

Mac

**Comment by rezrah** [comment]
Hey @simurai 👋 

This seems to be an issue with the custom class you're applying rather than the intersection observer itself. When you remove the custom class `className={styles['Hero__logo-letter']}`, it loads the underlying image fine for me on the first attempt. E.g:

(Viewable by GitHub Staff only)

https://github.com/github/primer/assets/13340707/34862aea-189f-4a5a-8c2f-c839d743da77

You shouldn't need to change the `visibilityOptions` at all. The following should be enough. I'd also recommend positioning AnimationProvider as the root of Hero.tsx instead of composing it near the logos. 

```jsx 
<AnimationProvider runOnce> 
```

Not sure yet what the solution is for making your animation work, but wanted to get a response out to you re. the suspected bug first. If you feel it is a bug however, can you provide an example without the custom classes?

**Comment by simurai** [comment]
> @rezrah an issue with the custom class

Thanks for trying it out. 🙇 Each image needs extra styling, so we can't really remove that, but I tried the following:

1. Wrap each image with `<Animate animate="slide-in-down">`
2. And lower the [distance override](https://github.com/github/githubuniverse.com/blob/e35f970240316e44ff059be4ce3e7c4b50c26879/components/generic/Hero/Hero.module.css#L99-L100) to just `50px`

And then it works great. So yeah.. it does seem that the custom styling is affecting things. Hmm.. Let's close this again. I might switch to an entirely custom implementation.. just because this project is short-lived and probably quite a unique case.
