### ISSUE TITLE
Improve Storybook quality - remove inconsistencies and add missing content

### ISSUE THREAD

**Issue by pouretrebelle** [primer/brand#656]
This is a tracking issue for improving the quality of our Storybook documentation, as part of https://github.com/github/primer/issues/3342

## Audit

This is based on the desired Storybook structure being:

- ComponentName
    - Playground - a story with controls to manipulate every prop of the component, and the external environment / child content as appropriate
    - Default - a story showing the most basic use of the component
    - Features - a folder of stories showing common configurations of the component, showcasing accessibility features, states, and sometimes displaying all the variations of one prop (e.g. ‘sizes’)
    - [ChildComponentName]
        - Playground, default, and feature stories

I discussed this with @rezrah but am open to alternative structures. I'll add a comment with more questions that have popped up over the audit.

<details>
<summary><strong>UX issues</strong></summary>

- [ ]  Component list is not alphabetical - forms, river, list, animation at bottom
- [ ]  Lack of intro page to show how to navigate the SB (what default, playground, features mean)
- [ ] No guidance on what stories to include for a component to be 'ready' - perhaps this could be a CI test in the future

</details>
<details>
<summary><strong>Undocumented features</strong></summary>

- [ ]  ActionMenu child components
    - [ ]  Button
    - [ ]  Overlay
    - [ ]  Item
- [ ]  AnchorNav child components
    - [ ]  Link
    - [ ]  Action
    - [ ]  SecondaryAction
- [ ]  Breadcrumbs.Item
- [ ]  Card child components
    - [ ]  Image
    - [ ]  Label
    - [ ]  Heading
    - [ ]  Description
- [ ]  ComparisonTable child components
- [ ]  CTABanner child components
    - [ ]  Heading
    - [ ]  Description
    - [ ]  ButtonGroup
- [ ]  CTAForm child components
    - [ ]  Input
    - [ ]  Confirm
    - [ ]  Action
- [ ]  EyebrowBanner child components
    - [ ]  Heading
    - [ ]  SubHeading
    - [ ]  Visual
    - [ ]  Label
- [ ]  FAQ child components
    - [ ]  Heading
    - [ ]  Subheading
    - [ ]  Item
    - [ ]  Question
    - [ ]  Answer
    - [ ]  FAQGroup (not a child of FAQ)
    - [ ]  FAQGroup.Heading
- [ ]  Hero child components
    - [ ]  Label
    - [ ]  Heading
    - [ ]  Description
    - [ ]  PrimaryAction
    - [ ]  SecondaryAction
    - [ ]  Image
- [ ]  IDE child components
    - [ ]  Editor
    - [ ]  Chat
- [ ]  LogoSuite child components
    - [ ]  Heading
    - [ ]  Description
    - [ ]  Logobar
- [ ]  MinimalFooter child components
    - [ ]  Link
    - [ ]  Footnotes
- [ ]  OrderedList.Item
- [ ]  UnorderedList.Item
- [ ]  Pillar child components
    - [ ]  Icon
    - [ ]  Heading
    - [ ]  Description
    - [ ]  Link
- [ ]  PricingOptions child components
    - [ ]  Item
    - [ ]  Heading
    - [ ]  Label
    - [ ]  Description
    - [ ]  Price
    - [ ]  FeatureList
    - [ ]  FeatureListHeading
    - [ ]  FeatureListItem
    - [ ]  Footnote
- [ ]  River child components
    - [ ]  Visual (for River and RiverBreakout)
    - [ ]  Content (for River and RiverBreakout)
- [ ]  RiverBreakout.A11yHeading
- [ ]  SectionIntro child components
    - [ ]  Heading
    - [ ]  Description
    - [ ]  Link
- [ ]  Statistic child components
    - [ ]  Heading
    - [ ]  Description
- [ ]  SubdomainNavBar.Link
- [ ]  SubNav child components
    - [ ]  Heading
    - [ ]  link
    - [ ]  Action
    - [ ]  SubMenu
- [ ]  Testimonial child components
    - [ ]  Name
    - [ ]  Avatar
    - [ ]  Logo
- [ ]  Timeline.Item
- [ ]  UnorderedList.Item
- [ ]  VideoPlayer child components
    - [ ]  Source
    - [ ]  Track
- [ ]  FormControl child components
    - [ ]  Label
    - [ ]  Validation
- [ ]  Select child components
    - [ ]  Option
    - [ ]  OptGroup
- [ ]  Grid.Column
- [ ]  hooks
    - [ ]  useAnchoredPosition
    - [ ]  useFocusTrap
    - [ ]  useIsomorphicLayoutEffect
    - [ ]  useKeyboardEscape
    - [ ]  useOnClickOutside
    - [ ]  useRef
    - [ ]  useResizeObserver
    - [ ]  useWindowSize

</details>
<details>
<summary><strong>Components missing a playground story</strong></summary>

- [ ]  ActionMenu playground (default story has controls)
- [ ]  Accordion
- [ ]  Bento
- [ ]  Bento.Item
- [ ]  Box
- [ ]  Breadcrumbs (exists but no controls)
- [ ]  CTAForm (exists but no controls)
- [ ]  ExpandableArrow
- [ ]  FAQ
- [ ]  Hero (default story has controls)
- [ ]  InlineLink
- [ ]  Label (exists but no controls)
- [ ]  Link
- [ ]  Pillar (exists but no controls)
- [ ]  PricingOptions
- [ ]  Prose (same as default, could make content-editable?)
- [ ]  SectionIntro (exists but no controls)
- [ ]  ThemeProvider (not needed?)
- [ ]  Timeline
- [ ]  Forms > Radio
- [ ]  Forms > Textarea (default story has controls)
- [ ]  River
- [ ]  RiverBreakout
- [ ]  RiverStoryScroll

</details>
<details>
<summary><strong>Components missing a default story</strong></summary>

- [ ]  ButtonGroup
- [ ]  ComparisonTable
- [ ]  Stack
- [ ]  SubdomainNavBar
- [ ]  Testimonial
- [ ]  Animation
- [ ]  Forms > Checkbox
- [ ]  FormControl
- [ ]  Forms > Select
- [ ]  Forms > TextInput

</details>
<details>
<summary><strong>Default story has controls</strong></summary>

- [ ]  AnchorNav
- [ ]  Avatar
- [ ]  Button
- [ ]  CTABanner
- [ ]  Card
- [ ]  EyebrowBanner
- [ ]  Grid
- [ ]  IDE
- [ ]  Image
- [ ]  LogoSuite
- [ ]  Statistic
- [ ]  VideoPlayer
- [ ]  UnorderedList

</details>
<details>
<summary><strong>Components with features that need nesting</strong></summary>

- [x]  Accordion
- [ ]  ButtonGroup
- [ ]  ComparisonTable
- [ ]  ExpandableArrow
- [ ]  Heading
- [ ]  InlineLink
- [ ]  Stack
- [ ]  Subnav
- [ ]  SubdomainNavBar
- [ ]  Testimonial
- [ ]  Text
- [ ]  Forms > Checkbox (variants grouped into one story)
- [ ]  River (some features are nested)
- [ ]  RiverBreakout

</details>

Not audited:

- Whether existing playground stories have every prop as a control
- Opportunities for new feature stories
- Consistency within feature stories (whether they have controls, whether they have multiple instances of the component in each story)
- Storybook addons

**Comment by pouretrebelle** [comment]
## Open questions

1. Should default stories have any controls?
    
    Currently a dozen or so have controls and look almost identical to their playground stories which feels redundant. IMO default should only have controls for required props.
    
2. Should feature stories have controls?
    
    I would lean towards no, as features should broadly be examples of how the component would commonly be used in situ, but this could be appropriate where a playground can’t replicate all views (for example an instance with very different content).
    
3. Capitalised ‘Playground’, ‘Default’ and ‘Features’ can get mixed up with capitalised component names, especially for nested components like Bento’s Item. Should we lowercase playground/default/features for clarity? I might be able to add some middlelayer code to do this to avoid having to add an extra line to each story’s code (`Playground.storyName = 'playground’`)
4. How should we handle grouped/nested components? Currently we have:
    - Bento has a child Item (matches code structure)
    - Forms are in a folder but have no root component (matches code structure)
    - River, RiverBreakout, RiverStoryScroll are documented as separate components but in the code are nested in a ‘river’ folder
    - OrderedList and UnorderedList are documented as unrelated components but in the code are nested in a ‘list’ folder
    
    AFAIK all components are exported from the top level, so should we have any grouping/nesting aside from child components? Or we could match the Storybook folders to the code structure.
    
    The docs site separates out Forms, Layout and Typography, that’s also an option.
    
5. How thorough should we be about having stories for child components?
    
    There are *a lot* of child components, I’ve listed all of them here for visibility. At the moment we only explicitly have stories for Bento.Item. Most of them are of the heading/description variety that wouldn’t be very helpful to have isolated stories of, but I’m not sure where that line of utility is so I’m leaning towards verbosity here as long as it doesn’t make component authoring too much of a slog. All the child component props are listed in the docs so it’s not like this information is inaccessible. Very interested on feedback for this one. This also feeds into question 3 - perhaps we should have a ‘components’ folder inside each of the parent components to contain these docs so the parent root doesn’t get too messy.

I’d especially be interested in hearing feedback from people who use this Storybook for building our marketing sites, what are your points of friction and are there any missing pieces of documentation you think should be higher priority?

**Comment by joshfarrant** [comment]
This is awesome, thanks so much for writing this up @pouretrebelle 🙌

I've got a few thoughts below; probably more questions than answers I'm afraid 😅

## Should default stories have any controls?

Do we need to have both _Playground_ and _Default_ stories? Since controls are enabled by default across all stories does the _Playground_ story even need to exist? I've not looked to see if there's ever much deviation between _Playground_ and _Default_ stories.

Have we looked at using [Storybook's Autodocs feature](https://storybook.js.org/docs/writing-docs/autodocs) to generate a basic docs page and playground for each component? It may remove the need for having _Playground_ and _Default_ stories at all, and would act as a more approachable landing page for each component, putting a component playground front and center.


## Should feature stories have controls?

I'll touch on this a bit further down.


## Story name casing

Follow-up question on this one — what's the reason for splitting out `features` stories? Some components (eg `Heading`) have them all together and tbh I quite like that I don't have to click into a sub-folder to see all of the stories.


## How should we handle grouped/nested components?

Interesting one, it would be great to get this consistent. What do you think to having a standard structure for all component stories which is something like:

```
ComponentName
├── Default
├── Feature
├── [...]
└── Feature
```

Then we can group certain components together at the top level.

```
Bento
├── Bento
│   ├── Default
│   ├── Feature
│   ├── [...]
│   └── Feature
│
└── Item
    ├── Default
    ├── Feature
    ├── [...]
    └── Feature
```


```
River
├── River
│   ├── Default
│   ├── Feature
│   ├── [...]
│   └── Feature
│
├── RiverBreakout
│   ├── Default
│   ├── Feature
│   ├── [...]
│   └── Feature
│
└── RiverStoryScroll
    ├── Default
    ├── Feature
    ├── [...]
    └── Feature
```


I'd be tempted to only do that for components that are exclusively designed to work together, as in the above examples. In that case the components we currently have in the _Forms_ folder could be brought out to the top level as they aren't built exclusively to work with one another, they just all happen to be form components.


## How thorough should we be about having stories for child components?

Very interesting points, figuring out a definitive place to draw that line could be tricky. It would be convenient if all of the information was in a single place so you didn't need to jump back to the docs, but I agree that having separate stories for them perhaps doesn't add much value a lot of the time. The fact that the child components exist at all is kind of an implementation detail. We could have built the same (parent) components with the same features using props instead of child components (the same way we do the `leadingComponent` prop on some components). That leads me to think they shouldn't have their own stories at all and should just be documented as features of the component in the same way as a component's props would be. That kind of invalidates my _Bento_ example above as, in that case, there would no longer need to be a folder named Bento, and all of the `Bento.Item` stories would actually just be features on the Bento component. I think that makes sense, because what is a `Bento` without a `Bento.Item` 🤔🤯

---

One other thought I had — would there be value in having a _Recipes_ folder inside certain components where it makes sense to do so?

I've picked Grid as a random example here

I'd consider the "features" of Grid (and Grid.Column) to be:

- The Grid can render as any HTML element you like
- The Grid can show an overlay to help with alignment
- The Grid can be full-width
- The Grid.Column can render as any HTML element you like
- The Grid.Column can span any number of columns (and can differ by breakpoint)
- The Grid.Column can start in any column you like (and can differ by breakpoint)

The stories we currently have in the _Features_ folder are:

- Asymmetry
- Nesting
- Responsive
- Centering
- Ratio: 50:50
- Ratio: 60:40
- Ratio 40:60
- Responsive Min Width

In my mind, that's more akin to a list of "recipes", rather than a list of "features".

I see the _features_  of a component basically just being the custom props that it accepts, and the _recipes_ are "hey look at these cool things you can do with this component". If its used widely enough and it makes sense to do so, then a recipe might graduate to being a feature one day by getting its own prop, at which point the recipe is removed and the prop is documented.

If we went down this path it probably wouldn't make sense for recipes to have controls.

**Comment by pouretrebelle** [comment]
Thanks for the feedback @joshfarrant! I was so focused on how we do things in PB I didn't think to check PRC/PVC, who have specific contributor docs on Storybook structure. [This ADR](https://github.com/github/primer/blob/main/adrs/2022-10-07-storybook-lookbook-story-format.md) explains the intended architecture and [this issue](https://github.com/github/primer/issues/1488) shows the refactor work for PRC.

I agree with you that having both default and playground feels a little redundant, but think in this case it would be better to go with the standard set by other Primer packages - it seems that default is used in the Storybook embeds on primer.style, while playground is only for when you open the Storybook itself, I think that's a sensible division for us to follow.

Re: features/recipes, I agree - 'features' seems to be a catchall for stories which don't explicitly show off features. The ADR recommends 'examples' as another folder for what you describe as recipes. I think going along with that pattern makes sense. I also think it's easier to have features+examples nested because then they can be their own files (e.g. `AnchorNav.features.stories.tsx`) which keeps the playground story file more readable and manageable. Having nesting folders also gives us a chance to have dev/testing folders for things like [autoplays](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-actionmenu-features--keyboard-navigation) without cluttering the root. I'd also like to peddle back my focus on casing 😅 as long as the file structure is consistent I don't think we need to worry about that.

Re: stories for child components, I think it's going to be hard to tell what's useful until I make a couple of examples. [This story for `EyebrowBanner`](https://stunning-chainsaw-j82glqz.pages.github.io/?path=/story/components-eyebrowbanner--playground) does a great job of showing controls for each child component within the playground, but that might not be suitable for components with a lot of flexibility 🤔 I'll play around and report back on this once I've done a lot of the grunt consistency bits.

**Comment by pouretrebelle** [comment]
Closing for private issue https://github.com/github/primer/issues/3635
