### ISSUE TITLE
[Modification Request] Add background image props to Hero component

### ISSUE THREAD

**Issue by jjwinskill** [primer/brand#793]
Many Primer Brand components, like `Section` and `BreakoutBanner`, follow a common pattern of accepting props that support a background image. We'd like to extend this pattern to the `Hero` component so we don't need a bespoke solution to using a background image with the `Hero`.

Specifically, would it be possible to add the following properties to the Hero component? (here I'm using `packages/react/src/Section/Section.tsx` for the sub types):

```ts
backgroundColor?: BackgroundColors | ResponsiveBackgroundColorMap
backgroundImageSrc?: string | string[] | ResponsiveBackgroundImageSrcMap
backgroundImagePosition?: string | string[] | ResponsiveBackgroundImagePositionMap
backgroundImageSize?: string | string[] | ResponsiveBackgroundImageSizeMap
```

This is similar to a separate request for the CTA banner https://github.com/primer/brand/issues/756

**Comment by rezrah** [comment]
Hi @jjwinskill 👋, thanks for putting in this request...

Do you have examples (designs / production pages) where you are applying background images directly to `Hero` please?

Asking because  `Hero` is internally grid-constrained, and therefore not suitable for applying background images directly to. Instead, you'll want to apply background colors and images to a parent `Section`, and allow the `Hero` to align automatically inside of it.

Let us know if that approach works for you, or doesn't. I'd be curious to learn how you're planning to use those background options were we to make them available.

**Comment by jjwinskill** [comment]
Hi @rezrah - Thanks for the follow up, and apologies that I'm just seeing this now.

That makes sense re: grid constraint. We do use a background image within our hero on a regular basis, some examples can be found at these pages:

- https://github.com/solutions
- https://github.com/newsroom
- https://github.com/enterprise/startups

Using a Section component is similar to how we're already solving this, so we can continue on with that. I'll close this request.
