### ISSUE TITLE
Issue with `AnchorNav` setting the primary action to be styled as a primary button

### ISSUE THREAD

**Issue by stamat** [primer/brand#826]
I wanted to style the primary action of the `AnchorNav.Action` as the primary button. It defaults to secondary styles. In order to use the primary button styles we need to have two buttons. I couldn't find anything in the docs. Maybe this is the intended behavior?

Anyway I came up with a hack for this... Is there a non hacky way to achieve this

![Image](https://github.com/user-attachments/assets/f5871964-0eef-458c-8290-ee70837ee1d4)

**Comment by rezrah** [comment]
> Maybe this is the intended behavior?

👋 @stamat that's correct. It's mentioned in our docs [here](https://primer.style/brand/components/AnchorNav#secondary-action).

![Image](https://github.com/user-attachments/assets/7e509051-f0c0-442b-8eb9-8a9348b1b0b7)

I recall the reason for going with secondary there was to not overpower the adjacent links.

**Comment by stamat** [comment]
@rezrah you think we should force the outline button if there is only one CTA? I mean that's ok with me, but not what we got in the designs... I personally prefer the primary action, and then if we have another one we use the secondary outline for it... But that's just my preference...

**Comment by rezrah** [comment]
@stamat It turns out that you can forward the `primary` variant to the action 👇 

```jsx
<AnchorNav>
  <AnchorNav.Action variant="primary">Sign up</AnchorNav.Action>
</AnchorNav>
```

![Image](https://github.com/user-attachments/assets/0078d632-514f-4f69-ae2a-42438e229d7b)

We're only providing sensible defaults in the component, not enforcing them. This means you can forward all the usual Button props to that component. This should meet the requirements of your request. 

FWIW we're going to make a few changes to AnchorNav following a convo with Site yesterday:

- Make buttons smaller
- Enforce primer/secondary pairing of two primaries are used

**Comment by stamat** [comment]
@rezrah ah TMYK! Thanks legend! ✨

**Comment by stamat** [comment]
@rezrah eeeeeerrrrrr.... I think I tried variant before...
![Image](https://github.com/user-attachments/assets/86abbc5e-1501-4447-989c-42d2784d61f8)

**Comment by rezrah** [comment]
Thanks for trying it @stamat, you're absolutely right, sorry for not noticing that. We're missing the type definitions to make this work in TS environments. I've opened a PR [here](https://github.com/primer/brand/pull/859)  that fixes this (and other things). Should land soon 🤞
