### ISSUE TITLE
Export `Icon` from the package

### ISSUE THREAD

**Issue by rfearing** [primer/brand#827]
`Icon` was released in release [`0.42.0`](https://github.com/primer/brand/releases) but not exported, so it can't be used.  It just needs to be exported from `packages/react/src/index.ts` I believe

**Comment by joshfarrant** [comment]
Hi @rfearing! 👋 Thanks for raising this.

When we introduced the component we made a conscious decision to keep it as an internal component for now. Currently, it's accessible through `Card.Icon` component and `Bento.Content[leadingVisual]` prop since these were the primary use cases we had in mind.

If you have specific use cases where you need `Icon` as a standalone component just let me know the specifics and we can reassess the decision 🙂

**Comment by rfearing** [comment]
@joshfarrant I think either I'm missing something obvious, or there was an oversight.

How do I put the `Icon` into the `Bento.Content[leadingVisual]` prop if `Icon` is never exported? In the [storybook story for Bento](https://github.com/primer/brand/blob/main/packages/react/src/Bento/Bento.stories.tsx), it is used as a relative import. I can't do that via an npm package.

I believe either the `Icon` component would need to be exported or a `Bento.Icon` created, right?

**Comment by joshfarrant** [comment]
Ah, you're absolutely right @rfearing, thank you for spotting this. It is indeed an oversight on my part!

@rezrah Are you happy for `Icon` to be exported as a public component? An alternative _could_ be to create a `Bento.Icon` component which reexports `Icon` (in the same way we do in `Card`) which could then be used inside the `leadingVisual` prop. wdyt?

**Comment by danielguillan** [comment]
Icon is now exported as of [Primer Brand v0.44](https://github.com/primer/brand/releases/tag/%40primer/react-brand%400.44.0). 🎉
